---
project_name: go-snapraid-web
before:
  hooks:
    - go mod tidy
builds:
  - main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.Version={{ .Tag }}
      - -X main.Commit={{ .FullCommit }}
dockers:
  - image_templates:
      - ghcr.io/gi8lino/go-snapraid-web:{{ .Tag }}-amd64
    use: buildx
    dockerfile: Dockerfile
    extra_files:
      - go.mod
      - go.sum
      - main.go
      - internal
      - web
    build_flag_templates:
      - --build-arg
      - LDFLAGS=-s -w -X main.Version={{ .Tag }} -X main.Commit={{ .FullCommit }}
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/gi8lino/go-snapraid-web
      - --label=org.opencontainers.image.source=https://github.com/gi8lino/go-snapraid-web
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses="GNU General Public License v3.0"
docker_manifests:
  - name_template: ghcr.io/gi8lino/go-snapraid-web:{{ .Tag }}
    image_templates:
      - ghcr.io/gi8lino/go-snapraid-web:{{ .Tag }}-amd64
  - name_template: ghcr.io/gi8lino/go-snapraid-web:latest
    image_templates:
      - ghcr.io/gi8lino/go-snapraid-web:{{ .Tag }}-amd64
